#ifndef _CV_PARAMS_H_ 
#define _CV_PARAMS_H_ 

#define TEST_SOURCE_PATH_ENV "TEST_SOURCE_PATH"

#if 0 //20000
#define TEST_DATA_CNT 13
#define TEST_HEADER_SIZE sizeof(size_t)
#define TEST_RAW_WIDTH 2448
#define TEST_RAW_HEIGHT 2048
#define TEST_RAW_DEPTH 8
#define TEST_RAW_SIZE ( TEST_RAW_WIDTH * TEST_RAW_HEIGHT * TEST_RAW_DEPTH / 8 )
#define TEST_DATA_SIZE ( TEST_HEADER_SIZE + TEST_RAW_SIZE )
#else
#define TEST_DATA_CNT 873
#define TEST_HEADER_SIZE ( sizeof(size_t) + sizeof(int) )
#define TEST_RAW_WIDTH 960
#define TEST_RAW_HEIGHT 1920
#define TEST_RAW_CHANNELS 3
#define TEST_RAW_DEPTH 8
#define TEST_RAW_SIZE ( TEST_RAW_WIDTH * TEST_RAW_HEIGHT * TEST_RAW_CHANNELS * TEST_RAW_DEPTH / 8 )
#define TEST_DATA_SIZE ( TEST_HEADER_SIZE + TEST_RAW_SIZE )
#endif

#define TEST_CONFIG_H2 810
#define TEST_CONFIG_H1 350
#define TEST_MAX_VALUE_THRESH 255
#define TEST_BLOCK_SIZE_THRESH 35
#define TEST_C_THRESH 5
#define TEST_SCALE 50


#endif //_CV_PARAMS_H_ 
